### PR TITLE
Feat/275-Changelog

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Updated the changelog with the recent changes.

### CODE REVIEW

**Comment by MRomalde** [comment]
Hi, this is a good job!! But only one thing , for me, the Student Acceptance is an increment in backend. Is not an improvement because there was nothing with the same behavior before. I think that change make the work better!

**Review by MRomalde — CHANGES_REQUESTED** [review]
Hi, this is a good job!! But only one thing , for me, the Student Acceptance is an increment in backend. Is not an improvement because there was nothing with the same behavior before. I think that change make the work better!

**Comment by FranciscoRossoR** [comment]
Thanks for the observation, you can check again now.

**Review by MRomalde — APPROVED** [review]
Thank you for looking at the feedback! it is a nice work!

**Pull request merged**
