### PR TITLE
Feature/94 customer agreement

### PR DESCRIPTION
**Pull request by manbarjim2**

### CODE REVIEW

**Review by MartaInes — CHANGES_REQUESTED** [review]
It's a good first approach, but there are a few things things that should be added to make it perfect:
- There ahould be a space for them to sign but also for us 
- The description of what we offer could be more specific or detailed
- It should include also how both of the parts are compromise in regards of the prototype testing, like when and how we are going to give it to them, and that they are going to try it and fulfill our forms before a deadline (check the Pilot User doc for more information)
- We should probably have another one for the Group 11 where only the part of the Pilot Users is included.

**Review by fracalrod3 — CHANGES_REQUESTED** [review]
I think it's pretty good, just missing a clearer explanation on prototyping and the client's feedback.

**Comment by manbarjim2** [comment]
The customer agreement has been made following the theoretical pill and the template they have given us. 
We need to add in our login that they accept this customer agreement.

**Review by fracalrod3 — APPROVED** [review]
I think it's a bit harsh, but it makes sense and seems alright,  it's a lot better explained and organised.

**Review by MartaInes — APPROVED** [review]
Great job!

**Review by fracalrod3 — APPROVED** [review]
Awesome!

**Pull request merged**
