### PR TITLE
Feature/217-Changelog

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Created the Sprint 3 changelog.

I still have some doubts so I'd like to hear some feedback, especially about:

- Did I miss any detail in the descriptions of features 78, 79 and 80 from backend?
- Should I include  backend task 170, about the bug log?
- Should I include any of the tasks related to the deploy? I din't include any currently because I didn't consider them directly related to the source code of the project.

If I missed anything else or I can still improve the document in any way, please let me know.

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
It looks good but in the part of the frontend when mentioned the part of the changes of the feedback given by the pilot user, I would add that the info has been given by the NGO and the group 11

**Review by pabpercab1 — CHANGES_REQUESTED** [review]
I think that in this document the important thing is not the issue title nor the number, which are the changes between versions. There should be visible changes between sprints, things that I am not seeing in the document either.

As an example:

**S1:**
_Features:_
- #44 Created the login form

**S2:**
_Features:_
- #55 Payment added in the app

_Improvements:_
- #66 Home page with more content

_Fixes:_
- #77 The login form had a bug with the cookies

**Review by claugp06 — CHANGES_REQUESTED** [review]
Now the document looks better and the changes are better seen but there are several spelling mistakes:
1. In the feature 40 of frontend the workd"conexión" it is not wirtten correctly
2. In the feature 52 spelling mistake "Creado del dropdown" it shoulbe either "creación del dropdown" or "creado el dropdown"
Apart from that the landing page it is not a task from the frontend but of documentation
In the fix 145 regarding about us, the dosier it not going to be included because of the denial of the NGO to send it so maybe you should change the sentence.
In the feedback from pilot users the "añadir educador" has not been changed to a button due to time contraints and not been a priority.
There is a spelling misktake regiradin where we are it should be "donde estamos"

**Review by claugp06 — CHANGES_REQUESTED** [review]
Looks good now but somenthing I want to comment is that I do not know if the payment will be finish for the delivery of S3 and also about the google log in it is done but not shown on the screens bcause a few more things needed it to be done to be working as we needed it and it is not a priority because it not sure if the NGO want it

**Review by claugp06 — CHANGES_REQUESTED** [review]
In feature 97/Educators-component it should be "añadida **la** cabacera" the "la" is missing
In feature/128 I would say that insteadof "subscripción" use "participación"
Some fixes that were done are missing such as the toast error one or the one related with fixing the profiles

**Comment by FranciscoRossoR** [comment]
> In feature 97/Educators-component it should be "añadida **la** cabacera" the "la" is missing In feature/128 I would say that insteadof "subscripción" use "participación" Some fixes that were done are missing such as the toast error one or the one related with fixing the profiles

I fixed the typos and the features mentioned are already registered

**Review by claugp06 — APPROVED** [review]
From my side (front) it seems ok

**Review by pabpercab1 — APPROVED** [review]
Look amazing! Well done

**Pull request merged**
