### PR TITLE
Feat/271-Plan de negocios

### PR DESCRIPTION
**Pull request by FranciscoRossoR**
Updated Sprint 3 Marketing Plan.

### CODE REVIEW

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
Some things I think you might need to improve:
- Add the miembros table as every other file has
- I would develop a bit more the introduction with what our company does
- In evaluacion de rentabilidad I would add the name of the files that contain that information (and probably add it on the ppl folder)

**Comment by FranciscoRossoR** [comment]
- Re-started the document following the feedback.
- Re-uploaded the referenced documents (the links leading to these documents may not work right now but are meant to work when merged, I'll fix if they don't).

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
I think this information should be added:
- the title should be for PPL not Sprint 3
- Add the subsections: 'Requisitos del cliente' and 'Idea refinada de negocio' from the developed-business-ideas file from the DP
- Add Competitor Analysis and a link to the file from DP copied on the PPL folder
- Change community manager for communication manager, since marta is the communicator manager and Aurora and I are communication manager
- Add also Marta as portavoz

**Review by marnunrey2 — APPROVED** [review]
Good job, I thinks it's ready now!

**Pull request merged**
