### PR TITLE
Feature/296 marketing plan

### PR DESCRIPTION
**Pull request by ivaramlar**
In this document, we have added a new plan of publications, in order to avoid the problems related to not receiving the feedback from Manos Abiertas con Norte.

### CODE REVIEW

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
- I would also include the tik of the things done in the first plan. 
- I would remove the week 4 if there is nothing planned yet or include something saying nothing planned yet
- Also keep on updating the file including the ticks on what you have done already (I can approve it at the end of the week)

**Comment by ivaramlar** [comment]
We have included the tik of the things done in the first plan and all the things done in plan b. There is a tik on Sunday because the content is already programmed, and It will be shown tomorrow.

Talking about the week 4, we need to say that the day 20 is the last day of the subject, this is why we have not planned anything later than this day.

**Review by marnunrey2 — CHANGES_REQUESTED** [review]
Looks good, just a quick detail, add a new row on the versions table with the person/people who have done the changes and add me as the reviewer

**Review by marnunrey2 — APPROVED** [review]
Perfect!

**Pull request merged**
