### PR TITLE
Feature/92-Impacto legal del proyecto

### PR DESCRIPTION
**Pull request by FranciscoRossoR**

### CODE REVIEW

**Review by claugp06 — CHANGES_REQUESTED** [review]
In the introduction you mention the creation of the web app of NexONG but we are not creating an app for ourselves it is for the NGO, explain this in more detail.
In the point 2 you mentioned the laws that exist and should be taken into consideration but you should explain more about what the laws are about us. For example in the case of Spain you mention the change of laws you could mention the differences.
In the point number 3, the ideas are good but can it be implemnted for example the data encription as said with the time and resources we have?
In the point number 4 in the first bullet point there is spelling mistake "informaicón" instead of "información". I would also recommend that instead of saying that some procedures should be establish, write more as we need to establish them and for that we are considering this, this and this.
In the point number 5 if you are using the plurarl you should use ONGs

**Comment by FranciscoRossoR** [comment]
Fixed an error in the content table and performed the following changes in each section:
1. Extended introduction.
2. Added differences in Spanish law.
3. Changed to options to consider instead of mandatory actions.
4. Same as 3 as requested, and fixed typo.
5. No changes. According to Spanish grammar, the plural form of initials is the same as the singular.

**Review by claugp06 — CHANGES_REQUESTED** [review]
Some concepts are not explain in the correct way for example in the intorduction: NexONG objetives it is to created webpages for NGOs that request it from us, we are not creating a wewb page for our organization

**Comment by FranciscoRossoR** [comment]
New changes:
- Changed the project goal in the introduction.
- Added GDPR explanation.
- Removed section about data encoding.
- Reworded policies and procedures section.

**Review by claugp06 — CHANGES_REQUESTED** [review]
In point number 2, the content improved but it will be better if you create a new pharagraph once you finished talking about the European laws.Also,you are using two ways of putting the laws "Reglamento General de Protección de Datos (RGPD)" and "la Ley Orgánica de Protección de Datos y Garantía de Derechos Digitales o LOPDGDD".Same format should be use and I think that it would be better to use the same format as the RGPD
In the point number 4 it woul be better expressed "Definición clara de quiénes tienen acceso a que información." instead the way it is expressed.

**Comment by FranciscoRossoR** [comment]
Performed requested changes.

**Review by claugp06 — APPROVED** [review]
Looks good now

**Pull request merged**
