### PR TITLE
170-bug-log

### PR DESCRIPTION
**Pull request by MRomalde**
Added bug log file that shows, the bugs that we discover with tests.

### CODE REVIEW

**Review by pedlopruz — CHANGES_REQUESTED** [review]
Good job, just several changes, there are two capital G's in the document, inspect the code with a control F to locate and remove them. On the other hand in the Bugs section you must indicate that all the roles failed

**Review by MartaInes — CHANGES_REQUESTED** [review]
Okay, let's go point by point:
- The title is incorrect, if you copy the strucutre of another document, make sure to change information)
- You put Pedro as the reviewer in the table, but I'm the reviewer of the PR
- The type of tests and number of them are missing, you should have a section where it appears the number of tests of each type

**Comment by MRomalde** [comment]
My bad with the title, I put Pedro as reviewer because he was the first reviewer, It is changed now! Of course the test types are added in the document

**Review by MartaInes — APPROVED** [review]
You could have put both of us as a reviewer, but the content of the document is okay,

**Review by pedlopruz — APPROVED** [review]
Good work

**Pull request merged**
