### PR TITLE
feature/89-matriz-raci

### PR DESCRIPTION
**Pull request by pedlopruz**
For this document, new roles have been included, in accordance with the current situation and updating the RACI matrix.

### CODE REVIEW

**Review by manortbla — APPROVED** [review]

**Review by MartaInes — CHANGES_REQUESTED** [review]
There are still missing some of the rols that they asked us to include last week, you can see them in the description of the issue.

**Comment by pedlopruz** [comment]
Thanks for the review, I forgot the rewiever role, I think all the roles are already written, if not, let me know and I'll quickly add them.

**Review by MartaInes — CHANGES_REQUESTED** [review]
Thanks for the changing it so fast! However, there are some things that could be improved:
- There is a misspelling in the line 164 where it says "maás"
- The role of Reviewer should also include the reviewers of documentation not only for code
- There should be also the role of Asignee (again being generic so it includes coding tasks but also documentation ones)

I think with that changes it'd be perfect.

**Comment by pedlopruz** [comment]
Perfect I make those changes, although I have some doubts about the role of Asignee because I consider that this is already part of the backend and frontend team, I do not see logical to have two roles that basically can stay in one, I do not know if I explain myself.

**Comment by MartaInes** [comment]
I think that in the Asignee they wanted us not only to show the responsabilities of the programmers but also the rersponsabilities of the people asignee to a documentation task.

**Comment by pedlopruz** [comment]
If so, instead of Asignee, I can set the role to Document Asignee and indicate that it is the one who performs the documentation tasks.

**Review by MartaInes — COMMENTED** [review]
Thanks for making all the changes :) 
I only noticed a small typo, there's an unnecessary comma in line 168 after "tiempo"

**Review by MartaInes — APPROVED** [review]
Great job! And thanks for making all the changes suggested.

**Pull request merged**
